
# -----------  Agents  -----------
[[agents]]
id = "test_agent2"
name = "HoloTester2"
public_address = "HcScJuDzSsGp5m7okmRrcIh76tKctdyckcnkbhOGTamy5yxjQX4Fe8nJVEv8bxz"
key_file = "/home/zo-el/.config/holochain/keys/HcScJuDzSsGp5m7okmRrcIh76tKctdyckcnkbhOGTamy5yxjQX4Fe8nJVEv8bxz"

# -----------  DNA  -----------
[[dnas]]
id = "fuel-dna"
file = "dna/holofuel.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "agent2_dna_instance"
dna = "fuel-dna"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec2.log"
[instances.storage]
type = "file"
path = "tmp-storage-1"

[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 4100
# [[interfaces.instances]]
# id = "agent1_dna_instance"
[[interfaces.instances]]
id = "agent2_dna_instance"
# -----------  UI  -----------

[[ui_bundles]]
id = "main2"
root_dir = "./ui-agent2"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface2"
bundle = "main2"
port = 9300
dna_interface = "websocket_interface"

# -----------  Networking  -----------
[network]
n3h_path = "/home/zo-el/n3h"
n3h_persistence_path = "/tmp"
bootstrap_nodes = [
"wss://192.168.0.7:34421/?a=hkbY7onOR6ej6JE_psua1LTucodEa67HAJidKbwW79kFhiqDrHvVAJ1Lgucu8lmAixF1PbFukKnsoXmryUJ2W-liCBZ5lots"
]
# NOTE: ONLY input following into toml file whenever being used >> this key is read and digested by n3h EVEN IF it is empty.
n3h_ipc_uri="wss://127.0.0.1:42943/"

# -----------  Networking instructions  -----------
# To get networking running requires the following steps:

# - Clone the repo for the holochain networking library n3h (https://github.com/holochain/n3h)
# - Checkout the tag in n3h for holochain v0.0.4-alpha (git fetch --tags && git checkout v0.0.4-alpha)
# - run `npm install && npm run boostrap` in the n3h directory
# - change the n3h_path above to point to the location where you cloned the repo

# - If you are the first node then start the conductor and take careful note of the line that
#	begins with `READY! tcp://127.0.0.1:43859 [...]
#	You will need to copy the contents of the array and send it to the nodes you plan to network with.
# - If you are a joining node then paste the contents from the first node in to the bootstrap_nodes field above
# - Make sure that you all have different agents for your instances (uncomment new agent and change the instances agent field)
# - Uncomment the network section and you should be ready do go!
