bridges = []

[[agents]]
id = "test agent 1"
key_file = "holo_tester.key"
name = "Holo Tester 1"
public_address = "HoloTester1-----------------------------------------------------------------------AAACZp4xHB"

[[agents]]
id = "test agent 2"
key_file = "holo_tester.key"
name = "Holo Tester 2"
public_address = "HoloTester2-----------------------------------------------------------------------AAAGy4WW9e"

[[ui_bundles]]
id = "bundle1"
root_dir = "./example-config/example-static-site"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface-1"
bundle = "bundle1"
port = 9800
dna_interface = "websocket interface 2"


[[dnas]]
file = "/home/lisa/Desktop/holofuelv5.hcpkg"
hash = "QmSFFbDHUmhSWP8pA3Z63pN4hqqgg91c3At9E4hucfVmSn"
id = "holofuelv4.hcpkg"

[[instances]]
agent = "test agent 2"
dna = "holofuelv4.hcpkg"
id = "holofuelv4.hcpkg instance"

[instances.storage]
path = "example-config/tmp-storage"
type = "file"


[[interfaces]]
admin = true
id = "websocket interface"

[interfaces.driver]
port = 3000
type = "websocket"

[[interfaces]]
admin = false
id = "http interface"

[[interfaces.instances]]
id = "holofuelv4.hcpkg instance"

[interfaces.driver]
port = 4000
type = "http"

[[interfaces]]
admin = false
id = "websocket interface 2"

[[interfaces.instances]]
id = "holofuelv4.hcpkg instance"

[interfaces.driver]
port = 3000
type = "websocket"
[logger]
type = "debug"
[[logger.rules.rules]]
color = "red"
exclude = false
pattern = "^err/"

[[logger.rules.rules]]
color = "white"
exclude = false
pattern = "^debug/dna"

[[logger.rules.rules]]
exclude = false
pattern = ".*"
