persistence_dir = '/home/lisa/.holochain/holo'
signing_service_uri = 'http://localhost:8888'

[[agents]]
id = 'host-agent'
keystore_file = '/home/lisa/.config/holochain/keys/HcSCj35Fgj7smCq4bxhtf7rrJS4v8pxxi66xtnwOh4mB3fvjIncm4Axaig8ng6r'
name = 'Envoy Host'
public_address = 'HcSCj35Fgj7smCq4bxhtf7rrJS4v8pxxi66xtnwOh4mB3fvjIncm4Axaig8ng6r'

# [[bridges]]
# callee_id = 'holofuel'
# caller_id = 'servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'
# handle = 'holofuel-bridge'

[[dnas]]
file = '/home/lisa/Documents/gitrepos/holochain/holo/holo-hosting/zo-el-hha-gui/holo-hosting-app_GUI/dna/HoloHostingApp/dist/HoloHostingApp.dna.json'
id = 'holo-hosting-app'

[[dnas]]
file = '/home/lisa/Documents/gitrepos/holochain/holo/holo-hosting/zo-el-hha-gui/holo-hosting-app_GUI/dna/HAppStore/dist/HAppStore.dna.json'
id = 'happ-store'

# Holofuel as Core App:
# [[dnas]]
# file = '/home/lisa/Documents/gitrepos/holochain/holo/envoy-intrceptr/envoy/src/dnas/holofuel/dist/holofuel.dna.json'
# id = 'holofuel'

[[dnas]]
file = '/home/lisa/.holochain/holo/dna/QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq.dna.json'
hash = 'QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'
id = 'QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'

[[dnas]]
file = '/home/lisa/.holochain/holo/dna/QmQaHNV34tuum6XbbK8d5UfkT9u9YZG1QQsbxAagmzsv5w.dna.json'
hash = 'QmQaHNV34tuum6XbbK8d5UfkT9u9YZG1QQsbxAagmzsv5w'
id = 'servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'

[[instances]]
agent = 'host-agent'
dna = 'holo-hosting-app'
id = 'holo-hosting-app'

[instances.storage]
path = '/home/lisa/.holochain/holo/storage/holo-hosting-app'
type = 'file'

[[instances]]
agent = 'host-agent'
dna = 'happ-store'
id = 'happ-store'

[instances.storage]
path = '/home/lisa/.holochain/holo/storage/happ-store'
type = 'file'

# Holofuel as Core App:
# [[instances]]
# agent = 'host-agent'
# dna = 'holofuel'
# id = 'holofuel'
#
# [instances.storage]
# path = '/home/lisa/.holochain/holo/storage/holofuel'
# type = 'file'

[[instances]]
agent = 'host-agent'
dna = 'QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'
id = 'QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'

[instances.storage]
path = '/home/lisa/.holochain/holo/storage/QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'
type = 'pickle'

[[instances]]
agent = 'host-agent'
dna = 'servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'
id = 'servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'

[instances.storage]
path = '/home/lisa/.holochain/holo/storage/servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'
type = 'pickle'

[[interfaces]]
admin = true
id = 'master-interface'

[[interfaces.instances]]
id = 'holo-hosting-app'

[[interfaces.instances]]
id = 'happ-store'

[interfaces.driver]
port = 1111
type = 'websocket'

[[interfaces]]
admin = false
id = 'public-interface'

[[interfaces.instances]]
id = 'QmYhReByy4kHs3tAdUGSSfUBhvkhTTcfFvnSBCqAr2KZpq'

[interfaces.driver]
port = 2222
type = 'websocket'

[[interfaces]]
admin = false
id = 'internal-interface'

[[interfaces.instances]]
id = 'servicelogger-QmPAggeesCovx9emG3MiqWENoPshHY15bNXKnCTE2nhKFy'

[interfaces.driver]
port = 3333
type = 'websocket'

[[ui_bundles]]
hash = 'Qm000'
id = 'bundle1'
root_dir = '/home/lisa/Documents/gitrepos/holochain/holo/holo-hosting/zo-el-hha-gui/holo-hosting-app_GUI/ui'

[[ui_bundles]]
hash = 'QmHAppStoreGUIFakeHash'
id = 'hAppStore-gui'
root_dir = '/home/lisa/Documents/gitrepos/holochain/holo/simulation-holo/HApps-Store/ui'

# Holofuel as Core App:
# [[ui_bundles]]
# hash = 'QmHolofuelGUIFakeHash'
# id = 'holofuel-gui'
# root_dir = '/home/lisa/Documents/gitrepos/holochain/holo/HoloFuel/holoFuelUI/temp/holofuel-gui/ui-zip/holo-master'

[[ui_interfaces]]
bundle = 'bundle1'
dna_interface = 'master-interface'
id = 'ui-interface-1'
port = 8000

[[ui_interfaces]]
bundle = 'hAppStore-gui'
dna_interface = 'master-interface'
id = 'hAppStore-gui-interface'
port = 8800

# Holofuel as Core App:
# [[ui_interfaces]]
# bundle = 'holofuel-gui'
# dna_interface = 'master-interface'
# id = 'holofuel-gui-interface'
# port = 9300

[logger]
type = 'debug'
[[logger.rules.rules]]
color = 'red'
exclude = false
pattern = '^err/'

[[logger.rules.rules]]
color = 'white'
exclude = false
pattern = '^debug/dna'

[[logger.rules.rules]]
exclude = true
pattern = '.*'
